UIFileReference =
{
	Academy = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	AfterBattle = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Alliance = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Armor = { ["s5cy5qnp"] = "UI/Library/Library" , ["rqtv1qew"] = "UI/GeneralBase/GeneralBase" , ["whwv8ghj"] = "UI/Alliance/Alliance" ,  },
	Bag = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Barrack = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Battle = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Bazaar = { ["s5cy5qnp"] = "UI/Library/Library" , ["4trbzbck"] = "UI/ItemIcon/ItemIcon" ,  },
	BuildersSpeedup = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Chat = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	ClimbingTower = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Farm = { ["s5cy5qnp"] = "UI/Library/Library" , ["lyv9eezh"] = "UI/Chat/Chat" ,  },
	FieldHeadquarters = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	General = { ["s5cy5qnp"] = "UI/Library/Library" , ["48zstrjk"] = "UI/EquipIcon/EquipIcon" , ["43m475k2"] = "UI/GeneralIconSmall/GeneralIconSmall" , ["rqtv1qew"] = "UI/GeneralBase/GeneralBase" , ["4auusrtu"] = "UI/GeneralIconLarge/GeneralIconLarge" , ["4trbzbck"] = "UI/ItemIcon/ItemIcon" ,  },
	GeneralBase = { ["s5cy5qnp"] = "UI/Library/Library" , ["rqtv1qew"] = "UI/GeneralBase/GeneralBase" ,  },
	Library = { ["rqtv1qew"] = "UI/GeneralBase/GeneralBase" , ["v7lqqrd6"] = "UI/ClimbingTower/ClimbingTower" , ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Login = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Lords = { ["s5cy5qnp"] = "UI/Library/Library" , ["5m2ue2jo"] = "UI/ScenePanel/ScenePanel" , ["4auusrtu"] = "UI/GeneralIconLarge/GeneralIconLarge" ,  },
	Mail = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	MainCity = { ["s5cy5qnp"] = "UI/Library/Library" , ["43m475k2"] = "UI/GeneralIconSmall/GeneralIconSmall" , ["5m2ue2jo"] = "UI/ScenePanel/ScenePanel" ,  },
	MonarchOrMainCityUpgrade = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Popup = { ["s5cy5qnp"] = "UI/Library/Library" , ["4trbzbck"] = "UI/ItemIcon/ItemIcon" , ["48zstrjk"] = "UI/EquipIcon/EquipIcon" ,  },
	PracticeHall = { ["s5cy5qnp"] = "UI/Library/Library" , ["rqtv1qew"] = "UI/GeneralBase/GeneralBase" ,  },
	PreBattle = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Pvp100Battle = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Ranking = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	ScenePanel = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Smithy = { ["s5cy5qnp"] = "UI/Library/Library" , ["48zstrjk"] = "UI/EquipIcon/EquipIcon" ,  },
	Task = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Tavern = { ["rqtv1qew"] = "UI/GeneralBase/GeneralBase" , ["v7lqqrd6"] = "UI/ClimbingTower/ClimbingTower" , ["s5cy5qnp"] = "UI/Library/Library" , ["4auusrtu"] = "UI/GeneralIconLarge/GeneralIconLarge" ,  },
	Tools = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Backroom = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Upgrade = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Wall = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	WarSituation = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
	Warehouse = { ["s5cy5qnp"] = "UI/Library/Library" ,  },
}

