-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('gm_pb')


local localTable = {}
S2CLISTCMDPROTO = protobuf.Descriptor()
localTable.S2CLISTCMDPROTO_DATAS_FIELD = protobuf.FieldDescriptor()
C2SGMPROTO = protobuf.Descriptor()
localTable.C2SGMPROTO_CMD_FIELD = protobuf.FieldDescriptor()
S2CGMPROTO = protobuf.Descriptor()
localTable.S2CGMPROTO_RESULT_FIELD = protobuf.FieldDescriptor()


localTable.S2CLISTCMDPROTO_DATAS_FIELD.name = "datas"
localTable.S2CLISTCMDPROTO_DATAS_FIELD.full_name = ".proto.S2CListCmdProto.datas"
localTable.S2CLISTCMDPROTO_DATAS_FIELD.number = 1
localTable.S2CLISTCMDPROTO_DATAS_FIELD.index = 0
localTable.S2CLISTCMDPROTO_DATAS_FIELD.label = 3
localTable.S2CLISTCMDPROTO_DATAS_FIELD.has_default_value = false
localTable.S2CLISTCMDPROTO_DATAS_FIELD.default_value = {}
localTable.S2CLISTCMDPROTO_DATAS_FIELD.type = 12
localTable.S2CLISTCMDPROTO_DATAS_FIELD.cpp_type = 9

S2CLISTCMDPROTO.name = "S2CListCmdProto"
S2CLISTCMDPROTO.full_name = ".proto.S2CListCmdProto"
S2CLISTCMDPROTO.nested_types = {}
S2CLISTCMDPROTO.enum_types = {}
S2CLISTCMDPROTO.fields = {localTable.S2CLISTCMDPROTO_DATAS_FIELD}
S2CLISTCMDPROTO.is_extendable = false
S2CLISTCMDPROTO.extensions = {}
localTable.C2SGMPROTO_CMD_FIELD.name = "cmd"
localTable.C2SGMPROTO_CMD_FIELD.full_name = ".proto.C2SGmProto.cmd"
localTable.C2SGMPROTO_CMD_FIELD.number = 1
localTable.C2SGMPROTO_CMD_FIELD.index = 0
localTable.C2SGMPROTO_CMD_FIELD.label = 1
localTable.C2SGMPROTO_CMD_FIELD.has_default_value = false
localTable.C2SGMPROTO_CMD_FIELD.default_value = ""
localTable.C2SGMPROTO_CMD_FIELD.type = 9
localTable.C2SGMPROTO_CMD_FIELD.cpp_type = 9

C2SGMPROTO.name = "C2SGmProto"
C2SGMPROTO.full_name = ".proto.C2SGmProto"
C2SGMPROTO.nested_types = {}
C2SGMPROTO.enum_types = {}
C2SGMPROTO.fields = {localTable.C2SGMPROTO_CMD_FIELD}
C2SGMPROTO.is_extendable = false
C2SGMPROTO.extensions = {}
localTable.S2CGMPROTO_RESULT_FIELD.name = "result"
localTable.S2CGMPROTO_RESULT_FIELD.full_name = ".proto.S2CGmProto.result"
localTable.S2CGMPROTO_RESULT_FIELD.number = 1
localTable.S2CGMPROTO_RESULT_FIELD.index = 0
localTable.S2CGMPROTO_RESULT_FIELD.label = 1
localTable.S2CGMPROTO_RESULT_FIELD.has_default_value = false
localTable.S2CGMPROTO_RESULT_FIELD.default_value = ""
localTable.S2CGMPROTO_RESULT_FIELD.type = 9
localTable.S2CGMPROTO_RESULT_FIELD.cpp_type = 9

S2CGMPROTO.name = "S2CGmProto"
S2CGMPROTO.full_name = ".proto.S2CGmProto"
S2CGMPROTO.nested_types = {}
S2CGMPROTO.enum_types = {}
S2CGMPROTO.fields = {localTable.S2CGMPROTO_RESULT_FIELD}
S2CGMPROTO.is_extendable = false
S2CGMPROTO.extensions = {}

C2SGmProto = protobuf.Message(C2SGMPROTO)
S2CGmProto = protobuf.Message(S2CGMPROTO)
S2CListCmdProto = protobuf.Message(S2CLISTCMDPROTO)

