-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('login_pb')


local localTable = {}
C2SINTERNALLOGINPROTO = protobuf.Descriptor()
localTable.C2SINTERNALLOGINPROTO_ID_FIELD = protobuf.FieldDescriptor()
S2CINTERNALLOGINPROTO = protobuf.Descriptor()
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD = protobuf.FieldDescriptor()
S2CLOGINPROTO = protobuf.Descriptor()
localTable.S2CLOGINPROTO_CREATED_FIELD = protobuf.FieldDescriptor()
localTable.S2CLOGINPROTO_MALE_FIELD = protobuf.FieldDescriptor()
localTable.S2CLOGINPROTO_HEAD_FIELD = protobuf.FieldDescriptor()
localTable.S2CLOGINPROTO_BUILDING_FIELD = protobuf.FieldDescriptor()
C2SCREATEHEROPROTO = protobuf.Descriptor()
localTable.C2SCREATEHEROPROTO_NAME_FIELD = protobuf.FieldDescriptor()
localTable.C2SCREATEHEROPROTO_MALE_FIELD = protobuf.FieldDescriptor()
S2CLOADEDPROTO = protobuf.Descriptor()
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD = protobuf.FieldDescriptor()


localTable.C2SINTERNALLOGINPROTO_ID_FIELD.name = "id"
localTable.C2SINTERNALLOGINPROTO_ID_FIELD.full_name = ".proto.C2SInternalLoginProto.id"
localTable.C2SINTERNALLOGINPROTO_ID_FIELD.number = 1
localTable.C2SINTERNALLOGINPROTO_ID_FIELD.index = 0
localTable.C2SINTERNALLOGINPROTO_ID_FIELD.label = 1
localTable.C2SINTERNALLOGINPROTO_ID_FIELD.has_default_value = false
localTable.C2SINTERNALLOGINPROTO_ID_FIELD.default_value = ""
localTable.C2SINTERNALLOGINPROTO_ID_FIELD.type = 9
localTable.C2SINTERNALLOGINPROTO_ID_FIELD.cpp_type = 9

C2SINTERNALLOGINPROTO.name = "C2SInternalLoginProto"
C2SINTERNALLOGINPROTO.full_name = ".proto.C2SInternalLoginProto"
C2SINTERNALLOGINPROTO.nested_types = {}
C2SINTERNALLOGINPROTO.enum_types = {}
C2SINTERNALLOGINPROTO.fields = {localTable.C2SINTERNALLOGINPROTO_ID_FIELD}
C2SINTERNALLOGINPROTO.is_extendable = false
C2SINTERNALLOGINPROTO.extensions = {}
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.name = "heroProto"
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.full_name = ".proto.S2CInternalLoginProto.heroProto"
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.number = 1
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.index = 0
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.label = 1
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.has_default_value = false
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.default_value = ""
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.type = 12
localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD.cpp_type = 9

S2CINTERNALLOGINPROTO.name = "S2CInternalLoginProto"
S2CINTERNALLOGINPROTO.full_name = ".proto.S2CInternalLoginProto"
S2CINTERNALLOGINPROTO.nested_types = {}
S2CINTERNALLOGINPROTO.enum_types = {}
S2CINTERNALLOGINPROTO.fields = {localTable.S2CINTERNALLOGINPROTO_HEROPROTO_FIELD}
S2CINTERNALLOGINPROTO.is_extendable = false
S2CINTERNALLOGINPROTO.extensions = {}
localTable.S2CLOGINPROTO_CREATED_FIELD.name = "created"
localTable.S2CLOGINPROTO_CREATED_FIELD.full_name = ".proto.S2CLoginProto.created"
localTable.S2CLOGINPROTO_CREATED_FIELD.number = 2
localTable.S2CLOGINPROTO_CREATED_FIELD.index = 0
localTable.S2CLOGINPROTO_CREATED_FIELD.label = 1
localTable.S2CLOGINPROTO_CREATED_FIELD.has_default_value = false
localTable.S2CLOGINPROTO_CREATED_FIELD.default_value = false
localTable.S2CLOGINPROTO_CREATED_FIELD.type = 8
localTable.S2CLOGINPROTO_CREATED_FIELD.cpp_type = 7

localTable.S2CLOGINPROTO_MALE_FIELD.name = "male"
localTable.S2CLOGINPROTO_MALE_FIELD.full_name = ".proto.S2CLoginProto.male"
localTable.S2CLOGINPROTO_MALE_FIELD.number = 3
localTable.S2CLOGINPROTO_MALE_FIELD.index = 1
localTable.S2CLOGINPROTO_MALE_FIELD.label = 1
localTable.S2CLOGINPROTO_MALE_FIELD.has_default_value = false
localTable.S2CLOGINPROTO_MALE_FIELD.default_value = false
localTable.S2CLOGINPROTO_MALE_FIELD.type = 8
localTable.S2CLOGINPROTO_MALE_FIELD.cpp_type = 7

localTable.S2CLOGINPROTO_HEAD_FIELD.name = "head"
localTable.S2CLOGINPROTO_HEAD_FIELD.full_name = ".proto.S2CLoginProto.head"
localTable.S2CLOGINPROTO_HEAD_FIELD.number = 4
localTable.S2CLOGINPROTO_HEAD_FIELD.index = 2
localTable.S2CLOGINPROTO_HEAD_FIELD.label = 1
localTable.S2CLOGINPROTO_HEAD_FIELD.has_default_value = false
localTable.S2CLOGINPROTO_HEAD_FIELD.default_value = ""
localTable.S2CLOGINPROTO_HEAD_FIELD.type = 9
localTable.S2CLOGINPROTO_HEAD_FIELD.cpp_type = 9

localTable.S2CLOGINPROTO_BUILDING_FIELD.name = "building"
localTable.S2CLOGINPROTO_BUILDING_FIELD.full_name = ".proto.S2CLoginProto.building"
localTable.S2CLOGINPROTO_BUILDING_FIELD.number = 5
localTable.S2CLOGINPROTO_BUILDING_FIELD.index = 3
localTable.S2CLOGINPROTO_BUILDING_FIELD.label = 3
localTable.S2CLOGINPROTO_BUILDING_FIELD.has_default_value = false
localTable.S2CLOGINPROTO_BUILDING_FIELD.default_value = {}
localTable.S2CLOGINPROTO_BUILDING_FIELD.type = 5
localTable.S2CLOGINPROTO_BUILDING_FIELD.cpp_type = 1

S2CLOGINPROTO.name = "S2CLoginProto"
S2CLOGINPROTO.full_name = ".proto.S2CLoginProto"
S2CLOGINPROTO.nested_types = {}
S2CLOGINPROTO.enum_types = {}
S2CLOGINPROTO.fields = {localTable.S2CLOGINPROTO_CREATED_FIELD, localTable.S2CLOGINPROTO_MALE_FIELD, localTable.S2CLOGINPROTO_HEAD_FIELD, localTable.S2CLOGINPROTO_BUILDING_FIELD}
S2CLOGINPROTO.is_extendable = false
S2CLOGINPROTO.extensions = {}
localTable.C2SCREATEHEROPROTO_NAME_FIELD.name = "name"
localTable.C2SCREATEHEROPROTO_NAME_FIELD.full_name = ".proto.C2SCreateHeroProto.name"
localTable.C2SCREATEHEROPROTO_NAME_FIELD.number = 1
localTable.C2SCREATEHEROPROTO_NAME_FIELD.index = 0
localTable.C2SCREATEHEROPROTO_NAME_FIELD.label = 1
localTable.C2SCREATEHEROPROTO_NAME_FIELD.has_default_value = false
localTable.C2SCREATEHEROPROTO_NAME_FIELD.default_value = ""
localTable.C2SCREATEHEROPROTO_NAME_FIELD.type = 9
localTable.C2SCREATEHEROPROTO_NAME_FIELD.cpp_type = 9

localTable.C2SCREATEHEROPROTO_MALE_FIELD.name = "male"
localTable.C2SCREATEHEROPROTO_MALE_FIELD.full_name = ".proto.C2SCreateHeroProto.male"
localTable.C2SCREATEHEROPROTO_MALE_FIELD.number = 2
localTable.C2SCREATEHEROPROTO_MALE_FIELD.index = 1
localTable.C2SCREATEHEROPROTO_MALE_FIELD.label = 1
localTable.C2SCREATEHEROPROTO_MALE_FIELD.has_default_value = false
localTable.C2SCREATEHEROPROTO_MALE_FIELD.default_value = false
localTable.C2SCREATEHEROPROTO_MALE_FIELD.type = 8
localTable.C2SCREATEHEROPROTO_MALE_FIELD.cpp_type = 7

C2SCREATEHEROPROTO.name = "C2SCreateHeroProto"
C2SCREATEHEROPROTO.full_name = ".proto.C2SCreateHeroProto"
C2SCREATEHEROPROTO.nested_types = {}
C2SCREATEHEROPROTO.enum_types = {}
C2SCREATEHEROPROTO.fields = {localTable.C2SCREATEHEROPROTO_NAME_FIELD, localTable.C2SCREATEHEROPROTO_MALE_FIELD}
C2SCREATEHEROPROTO.is_extendable = false
C2SCREATEHEROPROTO.extensions = {}
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.name = "heroProto"
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.full_name = ".proto.S2CLoadedProto.heroProto"
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.number = 1
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.index = 0
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.label = 1
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.has_default_value = false
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.default_value = ""
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.type = 12
localTable.S2CLOADEDPROTO_HEROPROTO_FIELD.cpp_type = 9

S2CLOADEDPROTO.name = "S2CLoadedProto"
S2CLOADEDPROTO.full_name = ".proto.S2CLoadedProto"
S2CLOADEDPROTO.nested_types = {}
S2CLOADEDPROTO.enum_types = {}
S2CLOADEDPROTO.fields = {localTable.S2CLOADEDPROTO_HEROPROTO_FIELD}
S2CLOADEDPROTO.is_extendable = false
S2CLOADEDPROTO.extensions = {}

C2SCreateHeroProto = protobuf.Message(C2SCREATEHEROPROTO)
C2SInternalLoginProto = protobuf.Message(C2SINTERNALLOGINPROTO)
S2CInternalLoginProto = protobuf.Message(S2CINTERNALLOGINPROTO)
S2CLoadedProto = protobuf.Message(S2CLOADEDPROTO)
S2CLoginProto = protobuf.Message(S2CLOGINPROTO)

