-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('misc_pb')


local localTable = {}
C2SHEARTBEATPROTO = protobuf.Descriptor()
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD = protobuf.FieldDescriptor()
S2CCONFIGPROTO = protobuf.Descriptor()
localTable.S2CCONFIGPROTO_CONFIG_FIELD = protobuf.FieldDescriptor()
C2SCLIENTLOGPROTO = protobuf.Descriptor()
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD = protobuf.FieldDescriptor()
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD = protobuf.FieldDescriptor()
C2SSYNCTIMEPROTO = protobuf.Descriptor()
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD = protobuf.FieldDescriptor()
S2CSYNCTIMEPROTO = protobuf.Descriptor()
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD = protobuf.FieldDescriptor()
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD = protobuf.FieldDescriptor()
S2CBLOCKPROTO = protobuf.Descriptor()
localTable.S2CBLOCKPROTO_DATA_FIELD = protobuf.FieldDescriptor()


localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.name = "client_time"
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.full_name = ".proto.C2SHeartBeatProto.client_time"
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.number = 1
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.index = 0
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.label = 1
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.has_default_value = false
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.default_value = 0
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.type = 5
localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD.cpp_type = 1

C2SHEARTBEATPROTO.name = "C2SHeartBeatProto"
C2SHEARTBEATPROTO.full_name = ".proto.C2SHeartBeatProto"
C2SHEARTBEATPROTO.nested_types = {}
C2SHEARTBEATPROTO.enum_types = {}
C2SHEARTBEATPROTO.fields = {localTable.C2SHEARTBEATPROTO_CLIENT_TIME_FIELD}
C2SHEARTBEATPROTO.is_extendable = false
C2SHEARTBEATPROTO.extensions = {}
localTable.S2CCONFIGPROTO_CONFIG_FIELD.name = "config"
localTable.S2CCONFIGPROTO_CONFIG_FIELD.full_name = ".proto.S2CConfigProto.config"
localTable.S2CCONFIGPROTO_CONFIG_FIELD.number = 1
localTable.S2CCONFIGPROTO_CONFIG_FIELD.index = 0
localTable.S2CCONFIGPROTO_CONFIG_FIELD.label = 1
localTable.S2CCONFIGPROTO_CONFIG_FIELD.has_default_value = false
localTable.S2CCONFIGPROTO_CONFIG_FIELD.default_value = ""
localTable.S2CCONFIGPROTO_CONFIG_FIELD.type = 12
localTable.S2CCONFIGPROTO_CONFIG_FIELD.cpp_type = 9

S2CCONFIGPROTO.name = "S2CConfigProto"
S2CCONFIGPROTO.full_name = ".proto.S2CConfigProto"
S2CCONFIGPROTO.nested_types = {}
S2CCONFIGPROTO.enum_types = {}
S2CCONFIGPROTO.fields = {localTable.S2CCONFIGPROTO_CONFIG_FIELD}
S2CCONFIGPROTO.is_extendable = false
S2CCONFIGPROTO.extensions = {}
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.name = "level"
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.full_name = ".proto.C2SClientLogProto.level"
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.number = 2
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.index = 0
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.label = 1
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.has_default_value = false
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.default_value = ""
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.type = 9
localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD.cpp_type = 9

localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.name = "text"
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.full_name = ".proto.C2SClientLogProto.text"
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.number = 1
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.index = 1
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.label = 1
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.has_default_value = false
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.default_value = ""
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.type = 9
localTable.C2SCLIENTLOGPROTO_TEXT_FIELD.cpp_type = 9

C2SCLIENTLOGPROTO.name = "C2SClientLogProto"
C2SCLIENTLOGPROTO.full_name = ".proto.C2SClientLogProto"
C2SCLIENTLOGPROTO.nested_types = {}
C2SCLIENTLOGPROTO.enum_types = {}
C2SCLIENTLOGPROTO.fields = {localTable.C2SCLIENTLOGPROTO_LEVEL_FIELD, localTable.C2SCLIENTLOGPROTO_TEXT_FIELD}
C2SCLIENTLOGPROTO.is_extendable = false
C2SCLIENTLOGPROTO.extensions = {}
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.name = "client_time"
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.full_name = ".proto.C2SSyncTimeProto.client_time"
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.number = 1
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.index = 0
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.label = 1
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.has_default_value = false
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.default_value = 0
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.type = 5
localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD.cpp_type = 1

C2SSYNCTIMEPROTO.name = "C2SSyncTimeProto"
C2SSYNCTIMEPROTO.full_name = ".proto.C2SSyncTimeProto"
C2SSYNCTIMEPROTO.nested_types = {}
C2SSYNCTIMEPROTO.enum_types = {}
C2SSYNCTIMEPROTO.fields = {localTable.C2SSYNCTIMEPROTO_CLIENT_TIME_FIELD}
C2SSYNCTIMEPROTO.is_extendable = false
C2SSYNCTIMEPROTO.extensions = {}
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.name = "client_time"
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.full_name = ".proto.S2CSyncTimeProto.client_time"
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.number = 1
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.index = 0
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.label = 1
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.has_default_value = false
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.default_value = 0
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.type = 5
localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD.cpp_type = 1

localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.name = "server_time"
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.full_name = ".proto.S2CSyncTimeProto.server_time"
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.number = 2
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.index = 1
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.label = 1
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.has_default_value = false
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.default_value = 0
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.type = 5
localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD.cpp_type = 1

S2CSYNCTIMEPROTO.name = "S2CSyncTimeProto"
S2CSYNCTIMEPROTO.full_name = ".proto.S2CSyncTimeProto"
S2CSYNCTIMEPROTO.nested_types = {}
S2CSYNCTIMEPROTO.enum_types = {}
S2CSYNCTIMEPROTO.fields = {localTable.S2CSYNCTIMEPROTO_CLIENT_TIME_FIELD, localTable.S2CSYNCTIMEPROTO_SERVER_TIME_FIELD}
S2CSYNCTIMEPROTO.is_extendable = false
S2CSYNCTIMEPROTO.extensions = {}
localTable.S2CBLOCKPROTO_DATA_FIELD.name = "data"
localTable.S2CBLOCKPROTO_DATA_FIELD.full_name = ".proto.S2CBlockProto.data"
localTable.S2CBLOCKPROTO_DATA_FIELD.number = 1
localTable.S2CBLOCKPROTO_DATA_FIELD.index = 0
localTable.S2CBLOCKPROTO_DATA_FIELD.label = 1
localTable.S2CBLOCKPROTO_DATA_FIELD.has_default_value = false
localTable.S2CBLOCKPROTO_DATA_FIELD.default_value = ""
localTable.S2CBLOCKPROTO_DATA_FIELD.type = 12
localTable.S2CBLOCKPROTO_DATA_FIELD.cpp_type = 9

S2CBLOCKPROTO.name = "S2CBlockProto"
S2CBLOCKPROTO.full_name = ".proto.S2CBlockProto"
S2CBLOCKPROTO.nested_types = {}
S2CBLOCKPROTO.enum_types = {}
S2CBLOCKPROTO.fields = {localTable.S2CBLOCKPROTO_DATA_FIELD}
S2CBLOCKPROTO.is_extendable = false
S2CBLOCKPROTO.extensions = {}

C2SClientLogProto = protobuf.Message(C2SCLIENTLOGPROTO)
C2SHeartBeatProto = protobuf.Message(C2SHEARTBEATPROTO)
C2SSyncTimeProto = protobuf.Message(C2SSYNCTIMEPROTO)
S2CBlockProto = protobuf.Message(S2CBLOCKPROTO)
S2CConfigProto = protobuf.Message(S2CCONFIGPROTO)
S2CSyncTimeProto = protobuf.Message(S2CSYNCTIMEPROTO)

