-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('stress_pb')


local localTable = {}
C2SROBOTPINGPROTO = protobuf.Descriptor()
localTable.C2SROBOTPINGPROTO_TIME_FIELD = protobuf.FieldDescriptor()
S2CROBOTPINGPROTO = protobuf.Descriptor()
localTable.S2CROBOTPINGPROTO_TIME_FIELD = protobuf.FieldDescriptor()


localTable.C2SROBOTPINGPROTO_TIME_FIELD.name = "time"
localTable.C2SROBOTPINGPROTO_TIME_FIELD.full_name = ".proto.C2SRobotPingProto.time"
localTable.C2SROBOTPINGPROTO_TIME_FIELD.number = 1
localTable.C2SROBOTPINGPROTO_TIME_FIELD.index = 0
localTable.C2SROBOTPINGPROTO_TIME_FIELD.label = 1
localTable.C2SROBOTPINGPROTO_TIME_FIELD.has_default_value = false
localTable.C2SROBOTPINGPROTO_TIME_FIELD.default_value = 0
localTable.C2SROBOTPINGPROTO_TIME_FIELD.type = 5
localTable.C2SROBOTPINGPROTO_TIME_FIELD.cpp_type = 1

C2SROBOTPINGPROTO.name = "C2SRobotPingProto"
C2SROBOTPINGPROTO.full_name = ".proto.C2SRobotPingProto"
C2SROBOTPINGPROTO.nested_types = {}
C2SROBOTPINGPROTO.enum_types = {}
C2SROBOTPINGPROTO.fields = {localTable.C2SROBOTPINGPROTO_TIME_FIELD}
C2SROBOTPINGPROTO.is_extendable = false
C2SROBOTPINGPROTO.extensions = {}
localTable.S2CROBOTPINGPROTO_TIME_FIELD.name = "time"
localTable.S2CROBOTPINGPROTO_TIME_FIELD.full_name = ".proto.S2CRobotPingProto.time"
localTable.S2CROBOTPINGPROTO_TIME_FIELD.number = 1
localTable.S2CROBOTPINGPROTO_TIME_FIELD.index = 0
localTable.S2CROBOTPINGPROTO_TIME_FIELD.label = 1
localTable.S2CROBOTPINGPROTO_TIME_FIELD.has_default_value = false
localTable.S2CROBOTPINGPROTO_TIME_FIELD.default_value = 0
localTable.S2CROBOTPINGPROTO_TIME_FIELD.type = 5
localTable.S2CROBOTPINGPROTO_TIME_FIELD.cpp_type = 1

S2CROBOTPINGPROTO.name = "S2CRobotPingProto"
S2CROBOTPINGPROTO.full_name = ".proto.S2CRobotPingProto"
S2CROBOTPINGPROTO.nested_types = {}
S2CROBOTPINGPROTO.enum_types = {}
S2CROBOTPINGPROTO.fields = {localTable.S2CROBOTPINGPROTO_TIME_FIELD}
S2CROBOTPINGPROTO.is_extendable = false
S2CROBOTPINGPROTO.extensions = {}

C2SRobotPingProto = protobuf.Message(C2SROBOTPINGPROTO)
S2CRobotPingProto = protobuf.Message(S2CROBOTPINGPROTO)

